spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_trading2?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Wh040309
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
  mail:
    host: smtp.qq.com
    port: 465
    username: 1494248473@qq.com
    password: vmygehppkmnfghii
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
           enable: true
  data:
    redis:
      host: localhost
      port: 6379
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.xxx.stock_trading_springboot.Bean

avatar:
  upload-dir: C:/Users/strive/IdeaProjects/Stock_trading_SpringBoot/uploads/avatar

